runtime: python
env: standard
instance_class: F1

env_variables:
  PORT: 8080

runtime_config:
  python_version: 3

entrypoint: streamlit run view.py --server.port $PORT

automatic_scaling:
  max_num_instances: 1
